debugging yml file again

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -18,12 +18,6 @@ jobs:
       - name: Running tests
         run: npx playwright test
       - name: debug test result steps
-        run: ls -R test-results
-      - name: uploading test results
-        if: always()
-        uses: actions/upload-artifact@v2
-        with:
-          name: Test Results
-          path: test-results
+        run: ls -R test-results || echo "test-results directory not found"
 
       
